import { NextRequest, NextResponse } from 'next/server'
import { createHmac, timingSafeEqual } from 'crypto'
import { supabase } from '@/lib/supabase'
import { requireSupabase } from '@/lib/guards'
import { checkRateLimit, getClientIP } from '@/lib/rate-limit'

/**
 * GET /api/unsubscribe?uid=<user_id>&token=<hmac>
 *
 * Validates the HMAC-SHA256 token generated by the weekly brief worker,
 * marks the subscription as inactive, and returns an HTML confirmation page.
 *
 * Security: uses timing-safe comparison to prevent timing attacks on the HMAC.
 */
export async function GET(request: NextRequest) {
  // Rate limit: 10 req/min to prevent brute-force token guessing
  const ip = getClientIP(request.headers)
  const rl = checkRateLimit(`unsubscribe:${ip}`, { max: 10, windowMs: 60_000 })
  if (!rl.allowed) {
    return NextResponse.json(
      { error: 'Too many requests' },
      {
        status: 429,
        headers: { 'Retry-After': String(Math.ceil(rl.retryAfterMs / 1000)) },
      }
    )
  }

  const guard = requireSupabase()
  if (guard) return guard

  const uid = request.nextUrl.searchParams.get('uid')
  const token = request.nextUrl.searchParams.get('token')

  if (!uid || !token) {
    return NextResponse.json(
      { error: 'Missing uid or token parameter' },
      { status: 400 }
    )
  }

  // Validate uid length to prevent abuse
  if (uid.length > 100 || token.length > 128) {
    return NextResponse.json(
      { error: 'Invalid parameters' },
      { status: 400 }
    )
  }

  // Compute expected HMAC and compare using timing-safe equality
  const secret = process.env.HMAC_SECRET ?? 'change-me-in-production'
  const expectedToken = createHmac('sha256', secret)
    .update(uid)
    .digest('hex')

  const tokenBuffer = Buffer.from(token, 'hex')
  const expectedBuffer = Buffer.from(expectedToken, 'hex')

  if (
    tokenBuffer.length !== expectedBuffer.length ||
    !timingSafeEqual(tokenBuffer, expectedBuffer)
  ) {
    return NextResponse.json(
      { error: 'Invalid or expired unsubscribe link' },
      { status: 403 }
    )
  }

  // Mark subscription as inactive
  try {
    const { error } = await supabase
      .from('email_subscriptions')
      .update({ active: false })
      .eq('user_id', uid)

    if (error) {
      console.error('[/api/unsubscribe] DB error:', error.message)
      return NextResponse.json(
        { error: 'Failed to process unsubscribe' },
        { status: 500 }
      )
    }
  } catch {
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }

  // Return a simple HTML confirmation page
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Unsubscribed</title>
  <style>
    body {
      font-family: system-ui, -apple-system, sans-serif;
      background: #09090b; color: #e4e4e7;
      display: flex; align-items: center; justify-content: center;
      min-height: 100vh; margin: 0;
    }
    .card {
      text-align: center; max-width: 400px; padding: 48px 32px;
      border: 1px solid #27272a; border-radius: 12px;
    }
    h1 { font-size: 20px; margin-bottom: 8px; }
    p { color: #a1a1aa; font-size: 14px; line-height: 1.5; }
    a { color: #3b82f6; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Unsubscribed successfully</h1>
    <p>You will no longer receive the weekly AI Intelligence Brief.</p>
    <p style="margin-top: 24px">
      <a href="/">Back to dashboard</a>
    </p>
  </div>
</body>
</html>`

  return new NextResponse(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
    },
  })
}
